"""Method A's eleven arms, as pure array math. NO torch, NO model, NO GPU.

`prereg_method_A.md` sections 3 and 4 define what gets written into a value
slot. That definition is arithmetic -- given the natural values of a prompt's
label rows, every arm's written vector is determined. Keeping it in one
torch-free module buys three things the preregistration actually needs:

  * section 11 gate 2 ("elementwise formula tests for LOO, global, wrong, same,
    norm-match, random-delta") can run anywhere, in a second, with no model;
  * the runner and any offline re-analysis share ONE definition of each arm,
    so an arm cannot drift between them (the class-space bug that cost two
    rounds came from exactly this kind of duplication);
  * the fixture can be written at TOKEN level while this module works at
    demo level, so the test is not generated by the code's own conventions
    (working rules rule 4 -- a fixture built from the implementation's assumptions
    can only ever prove self-consistency).

WHAT IS AND IS NOT HERE. This module builds VALUES. It does not choose
carriers, does not decide which token rows are label rows, and does not know
about GQA. Those belong to the runner, because they are properties of the
model, not of the arm.

SIGN AND SHRINKAGE CONVENTION (section 3). Every target arm writes

    v~_i = v0_i + gamma * (T_i - v0_i),

so gamma=0 is natural and gamma=1 lands exactly on T_i. random-delta is the one
arm defined on the displacement rather than on a target: it re-uses the raw-LOO
displacement's LENGTH with a fresh direction, which is what makes it a control
for "how far the write moved the value" rather than for "where it moved to".

The self-inclusive parameterization is NOT offered. Section 3 records that
including v0_i in the mean is only a reparameterization on the overlap
gamma_LOO = gamma_incl (1 - 1/N_c), and that LOO's gamma=1 is unreachable from
gamma_incl in [0,1] -- offering both would let the two be confused at the one
gamma that matters most.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field

import numpy as np

# The eleven preregistered arms (section 4 table), in the order they appear
# there. `natural` and `sham` write nothing; the rest are handled below.
ARMS = ("natural", "proto_loo", "single_same", "proto_normmatch", "proto_global",
        "proto_wrong", "rand_delta", "matched_heads", "pos_raw", "pos_dose",
        "sham")

# Arms whose written LABEL-row value comes from a target T_i.
TARGET_ARMS = ("proto_loo", "single_same", "proto_normmatch", "proto_global",
               "proto_wrong", "matched_heads")

GAMMA_GRID = (0.0, 0.25, 0.5, 0.75, 1.0)

EPS = 1e-12          # section 4's fixed guard, written into the formulas there
DERIVATION_SALT = 20260826


# --------------------------------------------------------------------------
# randomness
# --------------------------------------------------------------------------
def derive_seed(arm: str, setting: str, demo_seed: int, layer, carrier,
                demo_id) -> int:
    """SHA256(arm, setting, demo_seed, layer, head_or_group, demo_id, salt).

    Section 4 fixes this key so every random object is reproducible from the
    run's identity alone -- no RNG state is threaded through the code, and
    re-running one arm at one layer cannot disturb another.

    PROMPT-LEVEL OBJECTS USE SENTINELS. The wrong-class permutation is required
    by section 4 to be a FIXED derangement; if it were keyed on layer and head
    it would differ across the layers of a single prompt and demo i would be
    sent toward a different wrong class in each one, which is not a class
    -direction control at all. Such objects therefore pass layer=carrier=
    demo_id="*", which keeps them inside this key schema while making them
    constant over the axes they must be constant on.
    """
    key = "\0".join(str(x) for x in
                    (arm, setting, demo_seed, layer, carrier, demo_id,
                     DERIVATION_SALT))
    return int.from_bytes(hashlib.sha256(key.encode("utf-8")).digest()[:8],
                          "big")


def rng_for(arm, setting, demo_seed, layer, carrier, demo_id):
    return np.random.default_rng(derive_seed(arm, setting, demo_seed, layer,
                                             carrier, demo_id))


def derangement(classes, setting="L2", demo_seed=0):
    """A fixed permutation of `classes` with no fixed point (section 4).

    Rejection sampling rather than a shift or a cycle: a shift would make the
    wrong class a deterministic function of the true class's rank, so a "wrong
    class" effect could be produced by anything ordinal (adjacent label tokens,
    neighbouring rows in the label matrix) rather than by class identity.

    Deterministic given the class list -- same input, same derangement.
    """
    cs = list(classes)
    if len(cs) < 2:
        raise ValueError(
            f"a derangement of {len(cs)} class(es) does not exist, so the "
            "wrong-class arm is undefined for this prompt. Section 4 requires a "
            "permutation with no fixed point over the DISPLAYED classes; with "
            "fewer than two displayed classes there is no wrong class to send "
            "the demo toward.")
    rng = rng_for("proto_wrong", setting, demo_seed, "*", "*", "*")
    idx = np.arange(len(cs))
    for _ in range(10_000):
        p = rng.permutation(idx)
        if not np.any(p == idx):
            return {cs[i]: cs[int(p[i])] for i in range(len(cs))}
    raise RuntimeError("no derangement found; unreachable for len >= 2")


# --------------------------------------------------------------------------
# numerics
# --------------------------------------------------------------------------
def bf16_round(x):
    """Round float32 to bfloat16 precision, round-to-nearest-even, in numpy.

    Section 3.1 writes bf16(v~), so the fixtures have to be able to speak bf16
    without torch. This is the same rounding torch applies (test_prototype_
    targets.py checks it against torch elementwise when torch is importable).

    NaN and inf are rejected rather than special-cased: section 11 gate 13
    makes any NaN a freeze blocker, so a silent pass-through here would hide
    exactly what that gate exists to catch.
    """
    a = np.ascontiguousarray(x, dtype=np.float32)
    if not np.all(np.isfinite(a)):
        n_nan, n_inf = int(np.isnan(a).sum()), int(np.isinf(a).sum())
        raise ValueError(
            f"non-finite value before bf16 rounding: {n_nan} NaN, {n_inf} inf. "
            "This blocks the freeze (section 11 gate 13); find the source "
            "rather than clamping it here.")
    u = a.view(np.uint32)
    u = (u + (((u >> 16) & np.uint32(1)) + np.uint32(0x7FFF))) \
        & np.uint32(0xFFFF0000)
    return u.view(np.float32).reshape(a.shape)


# --------------------------------------------------------------------------
# class statistics
# --------------------------------------------------------------------------
def _check_class_counts(labels):
    labels = np.asarray(labels)
    cs, counts = np.unique(labels, return_counts=True)
    thin = {int(c): int(n) for c, n in zip(cs, counts) if n < 2}
    if thin:
        raise ValueError(
            f"displayed class(es) with N_c < 2: {thin}. Section 3 requires the "
            "whole prompt to fail before the run: the leave-one-out mean of a "
            "singleton class is undefined, and the two tempting fallbacks "
            "(self-inclusive mean, external bank) are both explicitly "
            "forbidden because they would silently change the operator.")
    return cs, counts


def class_means(v0, labels):
    """Full per-class means {c: mean over all demos of class c}."""
    v0 = np.asarray(v0, dtype=np.float64)
    labels = np.asarray(labels)
    return {int(c): v0[labels == c].mean(axis=0) for c in np.unique(labels)}


def loo_means(v0, labels):
    """mu_{y_i,-i} for every demo i (section 3). Shape [n, d].

    Computed from the class sum rather than by masking: (S_c - v_i)/(N_c - 1) is
    the same number and makes the N_c=1 division impossible to reach silently.
    """
    v0 = np.asarray(v0, dtype=np.float64)
    labels = np.asarray(labels)
    _check_class_counts(labels)
    out = np.empty_like(v0)
    for c in np.unique(labels):
        m = labels == c
        s = v0[m].sum(axis=0)
        n = int(m.sum())
        out[m] = (s - v0[m]) / (n - 1)
    return out


def same_class_donor(labels, demo_ids):
    """Index of each demo's single same-class donor (section 4, single-same).

    "Same-class demos in stable demo-ID cyclic order; i's donor is the next
    one." Stable ID, not row order: row order depends on how the prompt was
    assembled, so a donor map keyed on it would change whenever the renderer
    changed, and the arm would stop being reproducible from the manifest.
    """
    labels = np.asarray(labels)
    demo_ids = list(demo_ids)
    if len(set(demo_ids)) != len(demo_ids):
        raise ValueError(f"demo IDs must be unique to define a stable cyclic "
                         f"order; got {len(demo_ids)} ids, "
                         f"{len(set(demo_ids))} distinct")
    _check_class_counts(labels)
    donor = np.empty(len(labels), dtype=int)
    for c in np.unique(labels):
        rows = np.where(labels == c)[0]
        order = rows[np.argsort([str(demo_ids[r]) for r in rows], kind="stable")]
        for k, r in enumerate(order):
            donor[r] = order[(k + 1) % len(order)]
    return donor


# --------------------------------------------------------------------------
# the arms
# --------------------------------------------------------------------------
def arm_targets(arm, v0, labels, demo_ids, *, setting="L2", demo_seed=0):
    """Target T_i for every demo, for the target-valued arms (section 4).

    Returns [n, d] float64. `matched_heads` deliberately returns the raw-LOO
    target: section 4 defines it as "raw LOO rebuilt in the matched head's own
    basis", i.e. the same formula on a different carrier's values. The
    difference lives entirely in which v0 the caller passes in, and the fixture
    asserts these two agree so the distinction cannot quietly become a second
    formula.
    """
    v0 = np.asarray(v0, dtype=np.float64)
    labels = np.asarray(labels)
    if arm in ("proto_loo", "matched_heads"):
        return loo_means(v0, labels)
    if arm == "single_same":
        return v0[same_class_donor(labels, demo_ids)]
    if arm == "proto_normmatch":
        mu = loo_means(v0, labels)
        scale = (np.linalg.norm(v0, axis=1)
                 / (np.linalg.norm(mu, axis=1) + EPS))
        return mu * scale[:, None]
    if arm == "proto_global":
        # recipient's own class contributes its LOO mean, every other displayed
        # class its full mean, and the displayed classes are weighted EQUALLY --
        # not by how many demos they have. Equal weighting is what makes this
        # "averaging as such": a count-weighted version would mostly reproduce
        # the global mean of all demos and would confound averaging with class
        # frequency.
        mu_full = class_means(v0, labels)
        mu_loo = loo_means(v0, labels)
        cs = sorted(mu_full)
        base = np.sum([mu_full[c] for c in cs], axis=0)
        out = np.empty_like(v0)
        for i in range(len(v0)):
            c = int(labels[i])
            out[i] = (base - mu_full[c] + mu_loo[i]) / len(cs)
        return out
    if arm == "proto_wrong":
        pi = derangement(sorted({int(c) for c in labels}), setting, demo_seed)
        mu_full = class_means(v0, labels)
        # the FULL mean of the wrong class, not a leave-one-out mean: demo i is
        # not a member of pi(y_i), so there is nothing to leave out.
        return np.stack([mu_full[pi[int(c)]] for c in labels])
    raise ValueError(f"{arm!r} is not a target-valued arm; expected one of "
                     f"{TARGET_ARMS}")


def raw_delta(v0, labels):
    """Delta_i = mu_{y_i,-i} - v0_i (section 3).

    The displacement the main arm applies at gamma=1. The two position arms and
    random-delta are all defined against THIS displacement, not against their
    own, which is what makes them controls of equal magnitude.
    """
    return loo_means(v0, labels) - np.asarray(v0, dtype=np.float64)


def random_delta(v0, labels, *, setting, demo_seed, layer, carrier, demo_ids):
    """Delta^rand_i: a fresh Gaussian direction at the raw-LOO length."""
    v0 = np.asarray(v0, dtype=np.float64)
    lengths = np.linalg.norm(raw_delta(v0, labels), axis=1)
    out = np.empty_like(v0)
    for i, did in enumerate(demo_ids):
        rng = rng_for("rand_delta", setting, demo_seed, layer, carrier, did)
        r = rng.standard_normal(v0.shape[1])
        out[i] = r / (np.linalg.norm(r) + EPS) * lengths[i]
    return out


def written_label_rows(arm, gamma, v0, labels, demo_ids, *, setting="L2",
                       demo_seed=0, layer=0, carrier=0, cast_bf16=True):
    """The value written into each demo's label row. Shape [n, d].

    `natural` and `sham` return v0 unchanged -- they are in the same function on
    purpose, so that "the arm that writes nothing" travels down the same code
    path as the arms that do (section 11 gate 3 requires sham to execute the
    patch branch and still reproduce natural bitwise; a sham that skips the
    branch tests nothing).
    """
    if arm not in ARMS:
        raise ValueError(f"unknown arm {arm!r}; expected one of {ARMS}")
    v0 = np.asarray(v0, dtype=np.float64)
    if arm in ("natural", "sham"):
        return bf16_round(v0) if cast_bf16 else v0
    if arm in ("pos_raw", "pos_dose"):
        raise ValueError(
            f"{arm} does not write label rows -- section 4 keeps the label row "
            "natural and applies the displacement at a frozen non-label "
            "position. Use written_position_rows().")
    if not 0.0 <= float(gamma) <= 1.0:
        raise ValueError(f"gamma={gamma} outside the preregistered grid "
                         f"{GAMMA_GRID}")
    if arm == "rand_delta":
        d = random_delta(v0, labels, setting=setting, demo_seed=demo_seed,
                         layer=layer, carrier=carrier, demo_ids=demo_ids)
    else:
        d = arm_targets(arm, v0, labels, demo_ids, setting=setting,
                        demo_seed=demo_seed) - v0
    out = v0 + float(gamma) * d
    return bf16_round(out) if cast_bf16 else out


def written_position_rows(arm, gamma, v0_pos, delta, *, dose=None,
                          cast_bf16=True):
    """The value written at the frozen non-label position (section 4.2).

    v0_pos  [n, d]  natural values at the matched non-label positions
    delta   [n, d]  the RAW-LOO displacement of the same demo -- deliberately
                    not recomputed at this position, because the arm's job is
                    to inject the same vector somewhere else
    dose    [n] or [n, d]  per-head attention ratio s = alpha_label/alpha_pos,
                    required for pos_dose and forbidden for pos_raw

    pos_raw matches the injected NORM; pos_dose matches the validation-average
    first-order attention-weighted DOSE. They answer different questions and
    section 4.2 keeps both because matching one necessarily mismatches the
    other.
    """
    if arm not in ("pos_raw", "pos_dose"):
        raise ValueError(f"{arm!r} is not a position arm")
    v0_pos = np.asarray(v0_pos, dtype=np.float64)
    delta = np.asarray(delta, dtype=np.float64)
    if v0_pos.shape != delta.shape:
        raise ValueError(f"shape mismatch: positions {v0_pos.shape} vs "
                         f"displacements {delta.shape}")
    if arm == "pos_dose":
        if dose is None:
            raise ValueError("pos_dose needs the attention ratio s; without it "
                             "it is just pos_raw under another name")
        s = np.asarray(dose, dtype=np.float64)
        delta = delta * (s[:, None] if s.ndim == 1 else s)
    elif dose is not None:
        raise ValueError("pos_raw must not be scaled -- it is the equal-NORM "
                         "control (section 4.2)")
    out = v0_pos + float(gamma) * delta
    return bf16_round(out) if cast_bf16 else out


# --------------------------------------------------------------------------
# describing a write
# --------------------------------------------------------------------------
@dataclass
class LayerWrite:
    """What to overwrite in one layer's post-`repeat_kv` value tensor.

    rows    [R]  source token positions, i.e. the demo label rows
    values  {query_head: [R, d_head]}  the value each query head is to read

    A DESCRIPTION of a write, not the write itself, so it lives in the
    torch-free module: the runner builds these while planning, and its CPU
    fixture inspects them, neither of which should need a tensor library.
    tools/realized_write applies them.

    Values are given per query head EXPLICITLY rather than per KV group with
    implicit sharing. Under section 3.2 the four heads of a group normally do
    receive the same group target, but making that an input rather than a
    construction lets the fixture check it as a property -- and lets the
    single-head arm write one head without the code special-casing it.
    """
    rows: "object"
    values: dict = field(default_factory=dict)

    def heads(self):
        return sorted(int(h) for h in self.values)


# --------------------------------------------------------------------------
# carrier arithmetic
# --------------------------------------------------------------------------
# Which query heads share a KV slot is integer arithmetic, not a tensor
# operation, and both the arm construction and the write construction need it.
# It lives here, in the torch-free module, so that reasoning about carriers
# never drags in a torch import -- tools/realized_write re-exports it.
def group_of(head: int, n_attn_heads: int, n_kv_heads: int) -> int:
    """The KV group a query head reads from."""
    if n_attn_heads % n_kv_heads:
        raise ValueError(f"{n_attn_heads} query heads do not divide evenly "
                         f"into {n_kv_heads} KV heads")
    return int(head) // (n_attn_heads // n_kv_heads)


def group_members(group: int, n_attn_heads: int, n_kv_heads: int):
    """The query heads sharing a KV group -- the heads section 3.1 drags in."""
    if n_attn_heads % n_kv_heads:
        raise ValueError(f"{n_attn_heads} query heads do not divide evenly "
                         f"into {n_kv_heads} KV heads")
    w = n_attn_heads // n_kv_heads
    return list(range(int(group) * w, (int(group) + 1) * w))


def dose_scale(alpha_label, alpha_pos):
    """s = alpha_label / (alpha_pos + eps), section 4.2. Reported, never clipped.

    Section 4.2 says the distribution is reported in full and not clipped: a
    clip would silently turn the dose arm back into something between raw and
    dose, and the fraction clipped would then be a hidden hyperparameter.
    """
    return np.asarray(alpha_label, dtype=np.float64) / (
        np.asarray(alpha_pos, dtype=np.float64) + EPS)
